# Generated by Django 4.1.5 on 2023-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('date_of_movie_release', models.DateField()),
            ],
        ),
    ]
