# Generated by Django 4.1.5 on 2023-05-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_ottplatform_movielist_ott_platfor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ottplatform',
            name='movie_list',
        ),
    ]
