# Generated by Django 4.1.5 on 2023-05-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
