# Generated by Django 4.1.5 on 2023-05-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0007_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movielist',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
