# Generated by Django 4.1.5 on 2023-06-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0013_alter_movielist_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
